### ISSUE TITLE
[DB Secrets Configuration]Need to add Read Permission for server-key.pem file inside secrets folder for DB

### ISSUE THREAD

**Issue by vsrambix** [fido-device-onboard/pri-fidoiot#551] opened 2022-09-30 10:16 UTC
**Describe the bug**
Getting error "Failed to setup SSL" during DB start up when the Read permission is not added to server-key.pem file of DB generated by demo/scripts

**To Reproduce**
1. Generate the Secrets using demo_ca.sh, web_csr_req.sh, user_csr_req.sh & keys_gen.sh.
2. Copy the secrets folder to demo/db path.
3. Start the DB container and observe the DB logs.

**Expected behavior**
DB should get started without any errors

**Comment by Vishwasrao1** [comment] 2023-01-06 20:14
Are you sure this issue is fixed in release v1.1.4?  I can see no commits for database section in release v1.1.4. Moreover the issue is still there.

So without this the whole pri-fido-iot is of no use and just an imaginary documentation.

**Comment by Vishwasrao1** [comment] 2023-01-09 11:04
If anyone has this issue, please try using the below command to make it work.
`$ cd <pri-fidoiot>/component-samples/demo/db/secrets
 $ sudo chmod 400 server-key.pem
`

**Closed** 2023-07-27 11:29 UTC
